name: Cross Platform Tests
on:
  push:
jobs:
  Android-Tests:
    timeout-minutes: 15
    runs-on: macos-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SSH_KEY }}
      - name: Checkout submodules
        run: |
          git config --file .gitmodules --get-regexp url | while read url; do
            git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.SSH_KEY }}:${{ secrets.SSK_KEY }}@github.com\//")
          done
          git submodule sync
          git submodule update --init
      - name: Install Cocoapods
        run: sudo gem install cocoapods; sudo gem install cocoapods-generate
      - name: Run Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew runAndroid
      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: android-test-results
          path: com.mparticle.mockserver/build/reports/androidTests/connected/**
  iOS-Tests:
    runs-on: macOS-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SSH_KEY }}
      - name: Checkout submodules
        run: |
          git config --file .gitmodules --get-regexp url | while read url; do
            git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.SSH_KEY }}:${{ secrets.SSH_KEY }}@github.com\//")
          done
          git submodule sync
          git submodule update --init
      - name: Install Cocoapods
        run: sudo gem install cocoapods; sudo gem install cocoapods-generate
      - name: Run iOS cross platform tests
        run: ./gradlew runIos
      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ios-test-results
          path: Users/runner/Library/Developer/Xcode/DerivedData